name: automation
run-name: ${{github.actor}} activity triggered automation workflow

# Handy linter: https://rhysd.github.io/actionlint/

on:
  push:
    branches: [master,test_automation]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install YottaDB
        run: mkdir yottadb && cd yottadb && wget https://download.yottadb.com/ydbinstall.sh && chmod +x ydbinstall.sh && sudo ./ydbinstall.sh
      - name: Checkout MLua
        uses: actions/checkout@v4
      - name: Fetching
        run: make fetch
      - run: echo $ydb_dist && env
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - run: pwd && env
      - run: ls
      - run: ls mlua
      - run: cd mlua
      - name: Testing
        run: make test
