name: automation
run-name: ${{github.actor}} activity triggered automation workflow

# Handy linter: https://rhysd.github.io/actionlint/

on:
  push:
    branches: [master,test_automation]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MLua
        uses: actions/checkout@v4
      - name: Install YottaDB prerequisites
        run: sudo apt-get install -y --no-install-recommends file binutils libelf1 libicu-dev nano wget ca-certificates
      - name: Install YottaDB
        run: mkdir -p ydb_setup && cd ydb_setup && wget https://download.yottadb.com/ydbinstall.sh && chmod +x ydbinstall.sh && sudo ./ydbinstall.sh
      - name: Identify supported Lua builds  # for use in cache key
        id: luas
        run: "make --eval='print-luas: ; @echo luas=$(LUA_TEST_BUILDS)' print-luas >> $GITHUB_OUTPUT"

      - name: Restore cached Lua builds
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: |
            build/lua-*
            lua-yottadb
          key: "${{ runner.os }}-${{ steps.luas.outputs.luas }}"

      - name: Fetching and building supported Lua versions
        if: steps.restore-cache.outputs.cache-hit != 'true'
        run: make buildall

      - name: Save cached Lua builds
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: |
            build/lua-*
            lua-yottadb
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}

      - name: Testing
        run: make testall
