name: automation
run-name: ${{github.actor}} activity triggered automation workflow

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetching
        run: make fetch
  test:
    needs: setup
    steps:
      - name: Testing
        run: make test
