name: automation
run-name: ${{github.actor}} activity triggered automation workflow

# Handy linter: https://rhysd.github.io/actionlint/

on:
  push:
    branches: [master,test_automation]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MLua
        uses: actions/checkout@v4
      - name: Identify supported Lua builds  # for use in cache key
        run: "make --eval='print-luas: ; @echo LUA_TEST_BUILDS=$(LUA_TEST_BUILDS)' print-luas >> $GITHUB_ENV"
      - name: Cache setup
        id: cache-setup
        uses: actions/cache@v3
        with:
          path: |
            build/lua-*
            lua-yottadb
          key: "${{runner.os}}-luas=${{LUA_TEST_BUILDS}}"
      - name: Install YottaDB prerequisites
        run: sudo apt-get install -y --no-install-recommends file binutils libelf1 libicu-dev nano wget ca-certificates
      - name: Install YottaDB
        run: mkdir -p ydb_setup && cd ydb_setup && wget https://download.yottadb.com/ydbinstall.sh && chmod +x ydbinstall.sh && sudo ./ydbinstall.sh
      - name: Fetching supported Lua versions
        run: make fetchall
      - name: Fetching supported Lua versions
        run: make buildall

      - run: pwd && env
      - run: ls

      - name: Testing
        run: make test
