name: automation
run-name: ${{github.actor}} activity triggered automation workflow

on:
  push:
    branches: [master,test_automation]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install YottaDB
        run: mkdir /tmp/tmp && cd /tmp/tmp && wget https://download.yottadb.com/ydbinstall.sh && chmod +x ydbinstall.sh && ./ydbinstall.sh
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetching
        run: make fetch
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Testing
        run: make test
